# Generated by Django 5.0.4 on 2024-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorageapp', '0002_pdffile_delete_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
