# Generated by Django 5.0.4 on 2024-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorageapp', '0003_alter_pdffile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='file/'),
        ),
    ]
